package recommendation;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.DefaultListModel;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    static double num_first = 0.0;
    static double num_second = 0.0;
    static double num_third = 0.0;
    static double num_fourth = 0.0;
    static double num_fifth = 0.0;
    static int target_id;
    MovieRecommendation rec = new MovieRecommendation();

    public GUI() {
        initComponents();

        String filePath_main_data = "src\\main\\java\\recommendation\\main_data.csv";
        String filePath_movies = "src\\main\\java\\recommendation\\movies.csv";
        String filePath_target_user = "src\\main\\java\\recommendation\\target_user.csv";

        File main_data = new File(filePath_main_data);
        File target_user = new File(filePath_target_user);
        File movies = new File(filePath_movies);

        rec.LoadRatingsToTable(main_data);
        rec.LoadTargetsToTable(target_user);
        rec.loadMovieNames(movies);

        importTargetUsers();
        importRandomFilms(5, 10);

        int targetId = rec.getDummyTargetUser();
        User target = (User) rec.getTargetUsers().get(targetId);
        target_id = targetId;

    }

    private void importRandomFilms(int lists, int movies) {
        lists = 5;
        ArrayList<String[]> list0 = rec.getRandomMovieList(lists, movies);

        for (String movie : list0.get(0)) {
            cb_movie1.addItem(movie);
        }
        for (String movie : list0.get(1)) {
            cb_movie2.addItem(movie);
        }
        for (String movie : list0.get(2)) {
            cb_movie3.addItem(movie);
        }
        for (String movie : list0.get(3)) {
            cb_movie4.addItem(movie);
        }
        for (String movie : list0.get(4)) {
            cb_movie5.addItem(movie);
        }

    }

    private void importTargetUsers() {
        Hashtable<Integer, User> targetUsers = rec.getTargetUsers();
        Object[] targetUserIds = targetUsers.keySet().toArray();
        for (Object id : targetUserIds) {
            cb_target.addItem((String) id.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_target = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_recommend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_recommend = new javax.swing.JList<>();
        spin_x1 = new javax.swing.JSpinner();
        spin_k1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        cb_movie1 = new javax.swing.JComboBox<>();
        cb_movie2 = new javax.swing.JComboBox<>();
        cb_movie3 = new javax.swing.JComboBox<>();
        cb_movie4 = new javax.swing.JComboBox<>();
        cb_movie5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_recommend1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_recommend1 = new javax.swing.JList<>();
        btn_ma1 = new javax.swing.JButton();
        btn_ma2 = new javax.swing.JButton();
        btn_ma3 = new javax.swing.JButton();
        btn_ma4 = new javax.swing.JButton();
        btn_ma5 = new javax.swing.JButton();
        btn_mb5 = new javax.swing.JButton();
        btn_mb1 = new javax.swing.JButton();
        btn_mb4 = new javax.swing.JButton();
        btn_mb3 = new javax.swing.JButton();
        btn_mb2 = new javax.swing.JButton();
        btn_mc5 = new javax.swing.JButton();
        btn_mc1 = new javax.swing.JButton();
        btn_mc4 = new javax.swing.JButton();
        btn_mc3 = new javax.swing.JButton();
        btn_mc2 = new javax.swing.JButton();
        btn_md5 = new javax.swing.JButton();
        btn_md1 = new javax.swing.JButton();
        btn_md4 = new javax.swing.JButton();
        btn_md3 = new javax.swing.JButton();
        btn_md2 = new javax.swing.JButton();
        btn_me5 = new javax.swing.JButton();
        btn_me1 = new javax.swing.JButton();
        btn_me4 = new javax.swing.JButton();
        btn_me3 = new javax.swing.JButton();
        btn_me2 = new javax.swing.JButton();
        spin_x = new javax.swing.JSpinner();
        spin_k = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECOMMENDATION");
        setMinimumSize(new java.awt.Dimension(750, 750));
        setPreferredSize(new java.awt.Dimension(591, 614));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(51, 51, 51));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setForeground(new java.awt.Color(51, 51, 51));
        jToolBar1.setRollover(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Target User: ");

        cb_target.setMaximumRowCount(50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("K:");

        btn_recommend.setText("RECOMMEND");
        btn_recommend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recommendActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list_recommend);

        spin_x1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 400, 1));

        spin_k1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5401, 1));

        jLabel7.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(175, 57, 81));
        jLabel7.setText("Please Select Target User To Get The Closest Similarity ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_recommend, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spin_k1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spin_x1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_target, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_k1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_recommend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        jToolBar1.add(jPanel1);

        jTabbedPane1.addTab("User Recommendation", jToolBar1);

        jToolBar2.setBackground(new java.awt.Color(51, 51, 51));
        jToolBar2.setForeground(new java.awt.Color(51, 51, 51));
        jToolBar2.setRollover(true);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("K:");

        btn_recommend1.setText("RECOMMEND");
        btn_recommend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recommend1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(list_recommend1);

        btn_ma1.setText("1");
        btn_ma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ma1ActionPerformed(evt);
            }
        });

        btn_ma2.setText("2");
        btn_ma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ma2ActionPerformed(evt);
            }
        });

        btn_ma3.setText("3");
        btn_ma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ma3ActionPerformed(evt);
            }
        });

        btn_ma4.setText("4");
        btn_ma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ma4ActionPerformed(evt);
            }
        });

        btn_ma5.setText("5");
        btn_ma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ma5ActionPerformed(evt);
            }
        });

        btn_mb5.setText("5");
        btn_mb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mb5ActionPerformed(evt);
            }
        });

        btn_mb1.setText("1");
        btn_mb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mb1ActionPerformed(evt);
            }
        });

        btn_mb4.setText("4");
        btn_mb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mb4ActionPerformed(evt);
            }
        });

        btn_mb3.setText("3");
        btn_mb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mb3ActionPerformed(evt);
            }
        });

        btn_mb2.setText("2");
        btn_mb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mb2ActionPerformed(evt);
            }
        });

        btn_mc5.setText("5");
        btn_mc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mc5ActionPerformed(evt);
            }
        });

        btn_mc1.setText("1");
        btn_mc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mc1ActionPerformed(evt);
            }
        });

        btn_mc4.setText("4");
        btn_mc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mc4ActionPerformed(evt);
            }
        });

        btn_mc3.setText("3");
        btn_mc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mc3ActionPerformed(evt);
            }
        });

        btn_mc2.setText("2");
        btn_mc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mc2ActionPerformed(evt);
            }
        });

        btn_md5.setText("5");
        btn_md5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_md5ActionPerformed(evt);
            }
        });

        btn_md1.setText("1");
        btn_md1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_md1ActionPerformed(evt);
            }
        });

        btn_md4.setText("4");
        btn_md4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_md4ActionPerformed(evt);
            }
        });

        btn_md3.setText("3");
        btn_md3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_md3ActionPerformed(evt);
            }
        });

        btn_md2.setText("2");
        btn_md2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_md2ActionPerformed(evt);
            }
        });

        btn_me5.setText("5");
        btn_me5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_me5ActionPerformed(evt);
            }
        });

        btn_me1.setText("1");
        btn_me1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_me1ActionPerformed(evt);
            }
        });

        btn_me4.setText("4");
        btn_me4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_me4ActionPerformed(evt);
            }
        });

        btn_me3.setText("3");
        btn_me3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_me3ActionPerformed(evt);
            }
        });

        btn_me2.setText("2");
        btn_me2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_me2ActionPerformed(evt);
            }
        });

        spin_x.setModel(new javax.swing.SpinnerNumberModel(1, 1, 600, 1));

        spin_k.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5401, 1));

        jLabel4.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 57, 81));
        jLabel4.setText("Please Rate These Films To Get Your Recommendations ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cb_movie4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_md1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_md2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_md3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_md4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_md5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(cb_movie1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_ma1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_ma2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_ma3)
                                    .addGap(12, 12, 12)
                                    .addComponent(btn_ma4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_ma5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(cb_movie2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mb1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mb2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mb3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mb4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mb5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(cb_movie3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mc1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mc2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mc3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mc4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_mc5)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cb_movie5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_me1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_me2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_me3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_me4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_me5)))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spin_x)
                                    .addComponent(spin_k)))
                            .addComponent(btn_recommend1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_movie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ma1)
                    .addComponent(btn_ma2)
                    .addComponent(btn_ma3)
                    .addComponent(btn_ma4)
                    .addComponent(btn_ma5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_mc1)
                                    .addComponent(btn_mc2)
                                    .addComponent(btn_mc3)
                                    .addComponent(btn_mc4)
                                    .addComponent(btn_mc5)))
                            .addComponent(cb_movie3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_md5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_md1)
                                .addComponent(btn_md2)
                                .addComponent(btn_md3)
                                .addComponent(btn_md4)
                                .addComponent(cb_movie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_movie5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_me1)
                            .addComponent(btn_me2)
                            .addComponent(btn_me3)
                            .addComponent(btn_me4)
                            .addComponent(btn_me5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spin_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_mb5)
                            .addComponent(btn_mb4)
                            .addComponent(btn_mb3)
                            .addComponent(btn_mb2)
                            .addComponent(btn_mb1)
                            .addComponent(cb_movie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(spin_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_recommend1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jToolBar2.add(jPanel2);

        jTabbedPane1.addTab("Movie Recommendation", jToolBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ma1ActionPerformed

        if (btn_ma1.isEnabled()) {
            num_first = 1;
            btn_ma1.setBackground(Color.RED);
            btn_ma2.setBackground(Color.LIGHT_GRAY);
            btn_ma3.setBackground(Color.LIGHT_GRAY);
            btn_ma4.setBackground(Color.LIGHT_GRAY);
            btn_ma5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_ma1ActionPerformed

    private void btn_ma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ma2ActionPerformed

        if (btn_ma2.isEnabled()) {
            num_first = 2;
            btn_ma1.setBackground(Color.RED);
            btn_ma2.setBackground(Color.RED);
            btn_ma3.setBackground(Color.LIGHT_GRAY);
            btn_ma4.setBackground(Color.LIGHT_GRAY);
            btn_ma5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_ma2ActionPerformed

    private void btn_ma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ma3ActionPerformed

        if (btn_ma3.isEnabled()) {
            num_first = 3;
            btn_ma1.setBackground(Color.RED);
            btn_ma2.setBackground(Color.RED);
            btn_ma3.setBackground(Color.RED);
            btn_ma4.setBackground(Color.LIGHT_GRAY);
            btn_ma5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_ma3ActionPerformed

    private void btn_ma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ma4ActionPerformed

        if (btn_ma4.isEnabled()) {
            num_first = 4;
            btn_ma1.setBackground(Color.RED);
            btn_ma2.setBackground(Color.RED);
            btn_ma3.setBackground(Color.RED);
            btn_ma4.setBackground(Color.RED);
            btn_ma5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_ma4ActionPerformed

    private void btn_ma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ma5ActionPerformed

        if (btn_ma5.isEnabled()) {
            num_first = 5;
            btn_ma1.setBackground(Color.RED);
            btn_ma2.setBackground(Color.RED);
            btn_ma3.setBackground(Color.RED);
            btn_ma4.setBackground(Color.RED);
            btn_ma5.setBackground(Color.RED);
        }
    }//GEN-LAST:event_btn_ma5ActionPerformed

    private void btn_mb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mb1ActionPerformed

        if (btn_mb1.isEnabled()) {
            num_second = 1;
            btn_mb1.setBackground(Color.RED);
            btn_mb2.setBackground(Color.LIGHT_GRAY);
            btn_mb3.setBackground(Color.LIGHT_GRAY);
            btn_mb4.setBackground(Color.LIGHT_GRAY);
            btn_mb5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_mb1ActionPerformed

    private void btn_mb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mb2ActionPerformed

        if (btn_mb2.isEnabled()) {
            num_second = 2;
            btn_mb1.setBackground(Color.RED);
            btn_mb2.setBackground(Color.RED);
            btn_mb3.setBackground(Color.LIGHT_GRAY);
            btn_mb4.setBackground(Color.LIGHT_GRAY);
            btn_mb5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_mb2ActionPerformed

    private void btn_mb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mb3ActionPerformed

        if (btn_mb3.isEnabled()) {
            num_second = 3;
            btn_mb1.setBackground(Color.RED);
            btn_mb2.setBackground(Color.RED);
            btn_mb3.setBackground(Color.RED);
            btn_mb4.setBackground(Color.LIGHT_GRAY);
            btn_mb5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_mb3ActionPerformed

    private void btn_mb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mb4ActionPerformed

        if (btn_mb4.isEnabled()) {
            num_second = 4;
            btn_mb1.setBackground(Color.RED);
            btn_mb2.setBackground(Color.RED);
            btn_mb3.setBackground(Color.RED);
            btn_mb4.setBackground(Color.RED);
            btn_mb5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_mb4ActionPerformed

    private void btn_mb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mb5ActionPerformed

        if (btn_mb5.isEnabled()) {
            num_second = 5;
            btn_mb1.setBackground(Color.RED);
            btn_mb2.setBackground(Color.RED);
            btn_mb3.setBackground(Color.RED);
            btn_mb4.setBackground(Color.RED);
            btn_mb5.setBackground(Color.RED);
        }
    }//GEN-LAST:event_btn_mb5ActionPerformed

    private void btn_mc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mc1ActionPerformed

        if (btn_mc1.isEnabled()) {
            num_third = 1;
            btn_mc1.setBackground(Color.RED);
            btn_mc2.setBackground(Color.LIGHT_GRAY);
            btn_mc3.setBackground(Color.LIGHT_GRAY);
            btn_mc4.setBackground(Color.LIGHT_GRAY);
            btn_mc5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_mc1ActionPerformed

    private void btn_mc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mc2ActionPerformed

        if (btn_mc2.isEnabled()) {
            num_third = 2;
            btn_mc1.setBackground(Color.RED);
            btn_mc2.setBackground(Color.RED);
            btn_mc3.setBackground(Color.LIGHT_GRAY);
            btn_mc4.setBackground(Color.LIGHT_GRAY);
            btn_mc5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_mc2ActionPerformed

    private void btn_mc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mc3ActionPerformed

        if (btn_mc3.isEnabled()) {
            num_third = 3;
            btn_mc1.setBackground(Color.RED);
            btn_mc2.setBackground(Color.RED);
            btn_mc3.setBackground(Color.RED);
            btn_mc4.setBackground(Color.LIGHT_GRAY);
            btn_mc5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_mc3ActionPerformed

    private void btn_mc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mc4ActionPerformed

        if (btn_mc4.isEnabled()) {
            num_third = 4;
            btn_mc1.setBackground(Color.RED);
            btn_mc2.setBackground(Color.RED);
            btn_mc3.setBackground(Color.RED);
            btn_mc4.setBackground(Color.RED);
            btn_mc5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_mc4ActionPerformed

    private void btn_mc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mc5ActionPerformed

        if (btn_mc5.isEnabled()) {
            num_third = 5;
            btn_mc1.setBackground(Color.RED);
            btn_mc2.setBackground(Color.RED);
            btn_mc3.setBackground(Color.RED);
            btn_mc4.setBackground(Color.RED);
            btn_mc5.setBackground(Color.RED);
        }
    }//GEN-LAST:event_btn_mc5ActionPerformed

    private void btn_md1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_md1ActionPerformed

        if (btn_md1.isEnabled()) {
            num_fourth = 1;
            btn_md1.setBackground(Color.RED);
            btn_md2.setBackground(Color.LIGHT_GRAY);
            btn_md3.setBackground(Color.LIGHT_GRAY);
            btn_md4.setBackground(Color.LIGHT_GRAY);
            btn_md5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_md1ActionPerformed

    private void btn_md2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_md2ActionPerformed

        if (btn_md2.isEnabled()) {
            num_fourth = 2;
            btn_md1.setBackground(Color.RED);
            btn_md2.setBackground(Color.RED);
            btn_md3.setBackground(Color.LIGHT_GRAY);
            btn_md4.setBackground(Color.LIGHT_GRAY);
            btn_md5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_md2ActionPerformed

    private void btn_md3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_md3ActionPerformed

        if (btn_md3.isEnabled()) {
            num_fourth = 3;
            btn_md1.setBackground(Color.RED);
            btn_md2.setBackground(Color.RED);
            btn_md3.setBackground(Color.RED);
            btn_md4.setBackground(Color.LIGHT_GRAY);
            btn_md5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_md3ActionPerformed

    private void btn_md4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_md4ActionPerformed

        if (btn_md4.isEnabled()) {
            num_fourth = 4;
            btn_md1.setBackground(Color.RED);
            btn_md2.setBackground(Color.RED);
            btn_md3.setBackground(Color.RED);
            btn_md4.setBackground(Color.RED);
            btn_md5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_md4ActionPerformed

    private void btn_md5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_md5ActionPerformed

        if (btn_md5.isEnabled()) {
            num_fourth = 5;
            btn_md1.setBackground(Color.RED);
            btn_md2.setBackground(Color.RED);
            btn_md3.setBackground(Color.RED);
            btn_md4.setBackground(Color.RED);
            btn_md5.setBackground(Color.RED);
        }
    }//GEN-LAST:event_btn_md5ActionPerformed

    private void btn_me1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_me1ActionPerformed

        if (btn_me1.isEnabled()) {
            num_fifth = 1;
            btn_me1.setBackground(Color.RED);
            btn_me2.setBackground(Color.LIGHT_GRAY);
            btn_me3.setBackground(Color.LIGHT_GRAY);
            btn_me4.setBackground(Color.LIGHT_GRAY);
            btn_me5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_me1ActionPerformed

    private void btn_me2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_me2ActionPerformed

        if (btn_me2.isEnabled()) {
            num_fifth = 2;
            btn_me1.setBackground(Color.RED);
            btn_me2.setBackground(Color.RED);
            btn_me3.setBackground(Color.LIGHT_GRAY);
            btn_me4.setBackground(Color.LIGHT_GRAY);
            btn_me5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_me2ActionPerformed

    private void btn_me3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_me3ActionPerformed

        if (btn_me3.isEnabled()) {
            num_fifth = 3;
            btn_me1.setBackground(Color.RED);
            btn_me2.setBackground(Color.RED);
            btn_me3.setBackground(Color.RED);
            btn_me4.setBackground(Color.LIGHT_GRAY);
            btn_me5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_me3ActionPerformed

    private void btn_me4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_me4ActionPerformed

        if (btn_me4.isEnabled()) {
            num_fifth = 4;
            btn_me1.setBackground(Color.RED);
            btn_me2.setBackground(Color.RED);
            btn_me3.setBackground(Color.RED);
            btn_me4.setBackground(Color.RED);
            btn_me5.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_btn_me4ActionPerformed

    private void btn_me5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_me5ActionPerformed

        if (btn_me5.isEnabled()) {
            num_fifth = 5;
            btn_me1.setBackground(Color.RED);
            btn_me2.setBackground(Color.RED);
            btn_me3.setBackground(Color.RED);
            btn_me4.setBackground(Color.RED);
            btn_me5.setBackground(Color.RED);
        }
    }//GEN-LAST:event_btn_me5ActionPerformed

    private void btn_recommend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recommend1ActionPerformed
        // TODO add your handling code here:

        String movie1 = cb_movie1.getSelectedItem().toString();
        int movie1Id = rec.getIdFromMovieName(movie1);
        rec.addMovieRating(target_id, movie1Id, num_first, rec.getTargetUsers());

        String movie2 = cb_movie2.getSelectedItem().toString();
        int movie2Id = rec.getIdFromMovieName(movie2);
        rec.addMovieRating(target_id, movie2Id, num_second, rec.getTargetUsers());

        String movie3 = cb_movie3.getSelectedItem().toString();
        int movie3Id = rec.getIdFromMovieName(movie3);
        rec.addMovieRating(target_id, movie3Id, num_third, rec.getTargetUsers());

        String movie4 = cb_movie4.getSelectedItem().toString();
        int movie4Id = rec.getIdFromMovieName(movie4);
        rec.addMovieRating(target_id, movie4Id, num_fourth, rec.getTargetUsers());

        String movie5 = cb_movie5.getSelectedItem().toString();
        int movie5Id = rec.getIdFromMovieName(movie5);
        rec.addMovieRating(target_id, movie5Id, num_fifth, rec.getTargetUsers());

        int x = (int) spin_x.getValue();
        int k = (int) spin_k.getValue();

        ArrayList<String> movieList = rec.getRecommendations(target_id, x, k);
        DefaultListModel movieRec = new DefaultListModel();
        movieRec.addAll(movieList);
        list_recommend1.setModel(movieRec);


    }//GEN-LAST:event_btn_recommend1ActionPerformed

    private void btn_recommendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recommendActionPerformed
        // TODO add your handling code here:
        int x = (int) spin_x1.getValue();
        int k = (int) spin_k1.getValue();
        int id = Integer.parseInt(cb_target.getSelectedItem().toString());
        ArrayList<String> movieList = rec.getRecommendations(id, x, k);
        DefaultListModel movieRec = new DefaultListModel();
        movieRec.addAll(movieList);
        list_recommend.setModel(movieRec);
    }//GEN-LAST:event_btn_recommendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI movieRecommendation = new GUI();
                movieRecommendation.setLocationRelativeTo(null);
                movieRecommendation.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ma1;
    private javax.swing.JButton btn_ma2;
    private javax.swing.JButton btn_ma3;
    private javax.swing.JButton btn_ma4;
    private javax.swing.JButton btn_ma5;
    private javax.swing.JButton btn_mb1;
    private javax.swing.JButton btn_mb2;
    private javax.swing.JButton btn_mb3;
    private javax.swing.JButton btn_mb4;
    private javax.swing.JButton btn_mb5;
    private javax.swing.JButton btn_mc1;
    private javax.swing.JButton btn_mc2;
    private javax.swing.JButton btn_mc3;
    private javax.swing.JButton btn_mc4;
    private javax.swing.JButton btn_mc5;
    private javax.swing.JButton btn_md1;
    private javax.swing.JButton btn_md2;
    private javax.swing.JButton btn_md3;
    private javax.swing.JButton btn_md4;
    private javax.swing.JButton btn_md5;
    private javax.swing.JButton btn_me1;
    private javax.swing.JButton btn_me2;
    private javax.swing.JButton btn_me3;
    private javax.swing.JButton btn_me4;
    private javax.swing.JButton btn_me5;
    private javax.swing.JButton btn_recommend;
    private javax.swing.JButton btn_recommend1;
    private javax.swing.JComboBox<String> cb_movie1;
    private javax.swing.JComboBox<String> cb_movie2;
    private javax.swing.JComboBox<String> cb_movie3;
    private javax.swing.JComboBox<String> cb_movie4;
    private javax.swing.JComboBox<String> cb_movie5;
    private javax.swing.JComboBox<String> cb_target;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JList<String> list_recommend;
    private javax.swing.JList<String> list_recommend1;
    private javax.swing.JSpinner spin_k;
    private javax.swing.JSpinner spin_k1;
    private javax.swing.JSpinner spin_x;
    private javax.swing.JSpinner spin_x1;
    // End of variables declaration//GEN-END:variables
}
